version: "3.8"

services:
  db:
    image: postgres:14.2
    container_name: DevCamp-Postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "4321:5432"

  app:
    build: .
    image: product-house
    container_name: product-house-service
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
networks:
  back-end-devcamp-stack_default:
    external: true