spring.application.name=java-devcamp
server.port=7070

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:4321/postgres
spring.datasource.username=user
spring.datasource.password=password

# JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Swagger related properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger.html
# Swagger app url: http://localhost:7070/swagger-ui/index.html

# Path matching strategy
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
  

#Actuator endpoints
# Only expose endpoints you need instead of *
management.endpoints.web.exposure.include=health,info,metrics,loggers
info.app.name=Product Shop
info.app.description=Product management service
info.app.version=1.0.0
info.app.author=Ukechi Dikio
# Exclude sensitive endpoints if needed
management.endpoints.web.exposure.exclude=env,beans

# Optional: explicitly disable audit events to prevent auto-configuration errors
management.endpoint.audit.events.enabled=false
management.info.env.enabled=true

# Auth Service config
auth.service.url=http://localhost:8080/token
auth.service.client.username=admin@entelect.co.za
auth.service.client.password=password

#Rabbit MQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

#Notifications
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.test-connection=true

#OpenApi
remote.api.url=http://localhost:8082/status/