spring.application.name=java-devcamp
server.port=7070

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:4321/postgres
spring.datasource.username=user
spring.datasource.password=password

# JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Swagger related properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger.html
# Swagger app url: http://localhost:7070/swagger-ui/index.html

# Path matching strategy
spring.mvc.pathmatch.matching-strategy=ant_path_matcher